config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"

  get '/flights/search' => 'flights#search', :as => 'search_flights'
  post '/flights/search' => 'flights#results', :as => 'results_flights'

  resources :users
  resources :flights

  get '/sessions/new' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  get '/sessions/destroy' => 'sessions#destroy', :as => 'sessions_destroy'

  post '/flights/book/:id' => 'flights#book', :as => 'flight_book'
  get '/flights/cancel/:id' => 'flights#cancel', :as => 'flight_cancel'
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_and_belongs_to_many :users
  has_one :departure_airport
  has_one :arrival_airport
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :check_for_admin, only: [:new, :create, :update, :destroy]
  before_action :check_for_login

  def index
    match_flights_and_airports
  end

  def new
    @flight = Flight.new
  end

  def create
    # Collects the departure and arrival airports
    departure_airport = DepartureAirport.find flight_params[:departure_airport_id]
    arrival_airport = ArrivalAirport.find flight_params[:arrival_airport_id]
    # This conditional checks if the depature and arrival airports are in the same city
    unless departure_airport.city == arrival_airport.city
      # Creates a new flight
      flight = Flight.create flight_params
      if flight.save
        redirect_to flights_path
      else
        # Reloads the page in case of a failed submission
        render :new
      end
    else
      # Reloads the page if the departure and arrival airports are in the same city
      flash[:error] = "Error: Departure And Arrival Airports Can't Match"
      redirect_to new_flight_path
    end
  end

  def search
    # Collects the departure and arrival airports so they can be used in the selects
    @departure_airports = DepartureAirport.all
    @arrival_airports = ArrivalAirport.all
  end

  def results
    match_flights_and_airports
    # Checks if the user has selected a departure airport
    if params[:departure_airport].present?
      @desired_departure_airport = DepartureAirport.find params[:departure_airport]
    end
      # Checks if the user has selected an arrival airport
    if params[:arrival_airport].present?
      @desired_arrival_airport = ArrivalAirport.find params[:arrival_airport]
    end
    # Check for matching departure and arrival airports and return to search page if they match
    if params[:departure_airport].present? && params[:arrival_airport].present?
      if @desired_departure_airport.name == @desired_arrival_airport.name
        flash[:error] = "Airports Can't Match"
        redirect_to search_flights_path
        #TODO: Include a pop up stating that the airports can't match
      end
    end
    # Checks if the user has selected a date
    if params[:depart_time].present?
      @desired_date = params[:depart_time]
    end
  end

  def book
    flight = Flight.find params[:id]
    # Checks if a user hasn't already booked a flight and if there are seats available on the flight
    unless @current_user.flights.include?(flight) || flight.seats < 1
      # Adds a booking
      @current_user.flights.push(flight)
      # Reduces the available seat count after a booking
      flight.seats-=1
      flight.save
      redirect_to user_path(@current_user.id)
    else
      redirect_to search_flights_path
      # TODO include pop-ups warning about flights being already booked or full
    end
  end

  def cancel
    flight = Flight.find params[:id]
    if @current_user.flights.include?(flight)
      flash[:error] = "Cancelling Flight"
      # Removes a booking
      @current_user.flights.delete(flight)
      # Increases the available seat count after a booking is cancelled
      flight.seats+=1
      flight.save
    end
    redirect_to user_path(@current_user.id)
  end

  def show
    @flight = Flight.find params[:id]
    # Collect the departure and arrival airports
    @departure_airport = DepartureAirport.find @flight.departure_airport_id
    @arrival_airport = ArrivalAirport.find @flight.arrival_airport_id
    # Collect the airports' coordinates
    start_coordinates = Geokit::LatLng.new(@departure_airport.latitude, @departure_airport.longitude)
    target_coordinates = "#{@arrival_airport.latitude}, #{@arrival_airport.longitude}"
    # Use the geokit gem to find the distance
    distance = start_coordinates.distance_to(target_coordinates)
    plane_speed = 583 # The cruising speed of a Boeing 737 in miles
    # The travel time is calculated by dividing the distance by plane speed and adding 30 minutes to account for delays
    travel_time = (distance / plane_speed) + 0.5
    # The added (or lost) time from converting time zones is calculated and stored as timezone_change
    timezone_change = @arrival_airport.timezone_offset - @departure_airport.timezone_offset
    # The travel time and the timezone_change are added together, than multipled by 3600 to convert from hours into seconds
    @arrival_time = @flight.depart_time + ((travel_time + timezone_change) * 3600)
  end

  def update
    flight = Flight.find params[:id]
    departure_airport = DepartureAirport.find flight_params[:departure_airport_id]
    arrival_airport = ArrivalAirport.find flight_params[:arrival_airport_id]
    # This conditional checks if the depature and arrival airports are in the same city
    unless departure_airport.city == arrival_airport.city
      flight.update flight_params
    else
      flash[:error] = "Airports Can't Match"
    end
    redirect_to flight_path(flight.id)
  end

  def destroy
    flight = Flight.find params[:id]
    flash[:error] = "Deleting Flight"
    flight.destroy
    redirect_to flights_path
  end

  private
  def flight_params
    params.require(:flight).permit(:code, :depart_time, :seats, :departure_airport_id, :arrival_airport_id)
  end

  def match_flights_and_airports
    # Sorts the flights by departure time
    @flights = Flight.all.sort_by { |flight| flight.depart_time}
    # Create arrays for the depature and arrival airports
    @departure_airports = []
    @arrival_airports = []
    @flights.each_with_index do |flight, index|
      # Match departure airports with their flights
      @departure_airports[index] = DepartureAirport.find @flights[index].departure_airport_id
    end
    @flights.each_with_index do |flight, index|
      # Match arrival airports with their flights
      @arrival_airports[index] = ArrivalAirport.find @flights[index].arrival_airport_id
    end
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
  <div class="section-group">
    <%= form_for @flight do |f| %>
      <!-- All the properties are required, since a flight must have all this properties to be bookable -->
        <section>
          <div class="mb-3">
            <%= f.label :code %>
            <%= f.text_field :code, :required => true, :class => "form-control", :pattern => "[A-Z]{2}[0-9]{3}", :placeholder => "SU001" %>
          </div>
          <div class="mb-3">
            <%= f.label "From" %>
            <%= f.select :departure_airport_id, DepartureAirport.pluck(:city, :id), :required => true %>
          </div>
          <div class="mb-3">
            <%= f.label "Departs" %>
            <%= f.datetime_field :depart_time, :required => true, :class => "form-control", :min => Time.now.change({sec: 0}), :max => "31-12-2100 00:00:00", :step => 60 %>
          </div>

        </section>
        <section>

            <%= f.label :seats %>
            <%= f.number_field :seats, :required => true, :class => "form-control", :min => 1, :max => 1000 %>

            <%= f.label "Arrivals" %>
            <%= f.select :arrival_airport_id, ArrivalAirport.pluck(:city, :id), :required => true %>

            <%= f.submit "Submit", :class => "btn btn-success btn-lg" %>
        </section>

    <% end %>

  </div>

  <% if flash[:error].present? %>
      <p>
        <%= flash[:error] %>
      </p>
  <% end %>

app/views/flights/index.html.erb
<h2> All Flights</h2>

<div class="flight-list">
  <% @flights.each_with_index do |flight, index| %>
    <p>
      <%= link_to flight.code, flight_path(flight.id), :class => "flight-code" %>
      <%= flight.depart_time.strftime("%-d %B %Y, %I:%M%P") %> <%= @departure_airports[index].city %> to <%= @arrival_airports[index].city %>
    </p>

  <% end %>
</div>

<% if flash[:error].present? %>
  <%= javascript_tag 'alert("Flight Deleted")' %>
<% end %>

app/views/flights/new.html.erb
<h2>Create A New Flight</h2>

<%= render :partial => "form" %>

app/views/flights/results.html.erb
<h2>Search Results</h2>

<p>You searched for flights
  <%= "from #{@desired_departure_airport.city}" if @desired_departure_airport.present? %>
  <%= "to #{@desired_arrival_airport.city}" if @desired_arrival_airport.present? %>
  <%= "on #{Date.parse(@desired_date).strftime("%-d %B %Y")}" if @desired_date.present? %>
</p>

<div class="flight-list">

  <% count = 0 %>
  <% @flights.each_with_index do |flight, index| %>
    <% if @desired_departure_airport.present? && @departure_airports[index] != @desired_departure_airport %>
    <% elsif @desired_arrival_airport.present? && @arrival_airports[index] != @desired_arrival_airport %>
    <% elsif @desired_date.present? && @desired_date != flight.depart_time.to_s.slice(0, 10) %>
    <% else %>
      <p>
        <%= link_to flight.code, flight_path(flight.id) %> Departs: <%= @departure_airports[index].city %> on <%= flight.depart_time.strftime("%-d %B %Y, %I:%M%P") %>, Arrives: <%= @arrival_airports[index].city %>
        <% count +=1 %>
      </p>
    <% end %>
  <% end %>

</div>

<p><%= "Sorry, no flights found. Try searching again with different filters." if count == 0 %></p>

app/views/flights/search.html.erb
<h2>Search For Flights</h2>

<%= form_tag  do %>

  <p>
    <%= label_tag "Departure City", nil, :for => "departure_airport" %>
    <select id="departure_airport" name="departure_airport">
      <option value=""></option>
      <% @departure_airports.each do |airport| %>
        <option value="<%= airport.id %>"><%= airport.city %></option>
      <% end %>
    </select>

    <%= label_tag "Arrival City", nil, :for => "arrival_airport" %>
    <select id="arrival_airport" name="arrival_airport">
        <option value=""></option>
      <% @arrival_airports.each do |airport| %>
        <option value="<%= airport.id %>"><%= airport.city %></option>
      <% end %>
    </select>

  </p>

  <p>
    <%= label_tag "Departure Date" %>
    <%= date_field_tag :depart_time %>

    <%= submit_tag "Apply Filters", :class => "btn btn-dark btn-lg" %>
  </p>

<% end %>

<% if flash[:error].present? %>
  <%= javascript_tag 'alert("Departure And Arrival Airports Cannot Match")' %>
<% end %>

app/views/flights/show.html.erb
<h2><%= @flight.code %></h2>

<p><strong>Departure Airport:</strong> <%= @departure_airport.name %> in <%= @departure_airport.city %> </p>
<p><strong>Departure Time:</strong> <%= @flight.depart_time.strftime("%-d %B %Y, %I:%M%P") %>, local time</p>

<p><strong>Arrival Airport:</strong> <%= @arrival_airport.name %> in <%= @arrival_airport.city %> </p>
<p><strong>Arrival Time (estimated):</strong> <%= @arrival_time.strftime("%-d %B %Y, %I:%M%P") %>, local time </p>

<p>
  <strong>Seats Available:</strong> <%= @flight.seats %>
  <% if @flight.seats < 1 %>
    <%= link_to "Flight Full", {}, :disabled => true, :method => "post", :class => "btn btn-danger btn-lg disabled" %>
  <% elsif @current_user.flights.include?(@flight) %>
    <%= link_to "Flight Already Booked", {}, :disabled => true, :method => "post", :class => "btn btn-danger btn-lg disabled" %>
  <% else %>
    <%= link_to "Book Flight", flight_book_path, :method => "post", :class => "btn btn-success btn-lg" %>
  <% end %>
</p>

<% if @current_user.admin? %>

    <h3>Edit Flight Details</h3>

    <%= render :partial => "form" %>

    <%= button_to "Delete Flight", @flight, :method => "delete", :class => "btn btn-danger btn-lg" %>

<% end %>