config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"

  get '/flights/search' => 'flights#search', :as => 'search_flights'
  post '/flights/search' => 'flights#results', :as => 'results_flights'

  resources :users
  resources :flights

  get '/sessions/new' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  get '/sessions/destroy' => 'sessions#destroy', :as => 'sessions_destroy'

  post '/flights/book/:id' => 'flights#book', :as => 'flight_book'
  get '/flights/cancel/:id' => 'flights#cancel', :as => 'flight_cancel'
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :flights
  has_secure_password
  validates :email, :uniqueness => true, :presence => true #validations
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, only: [:index]
  before_action :check_for_no_login, only: [:new, :create]
  before_action :check_for_specific_user, only: [:update, :show, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.save
      # Automatically log the user in after they sign up
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to user_path(user.id)
  end

  def show
    @user = User.find params[:id]
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :mobile, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h2>User List</h2>

<% @users.each do |user| %>
  <div class="details">
    <p>
      <%= link_to user.name, user_path(user.id) %>,
      Email: <%= user.email %>,
      Mobile: <%= user.mobile %>
    </p>
  </div>

<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= form_for @user do |f| %>
  <section>
    <div class="mb-3">
      <%= f.label :name, :class => 'form-label' %>
      <%= f.text_field :name, :required => true, :class => "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :email %>
      <%= f.email_field :email, :required => true, :class => 'form-control' %>
    </div>

    <div class="mb-3">
      <%= f.label :mobile %>
      <%= f.text_field :mobile, :class => "form-control" %>
    </div>
  </section>

  <section>
    <div class="mb-3">
      <%= f.label :password %>
      <%= f.password_field :password, :required => true, :class => "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, :required => true, :class => "form-control", :id => "confirm-password"  %>
    </div>

    <%= f.submit "Sign Up!", :class => "btn btn-dark btn-lg" %>
  </section>

<% end %>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <p>-<%= msg %></p>
    <% end %>
<% end %>

app/views/users/show.html.erb
<h2>Booked Flights</h2>

<% unless @user.flights.length < 1 %>
  <div class="row">
    <% @user.flights.each do |flight| %>
      <div class="col-2">
        <%= link_to flight.code, flight_path(flight.id) %>
        <%= button_to "Cancel Booking", flight_cancel_path(flight.id), :method => 'get', :class => "btn btn-danger btn-sm" %>
      </div>
    <% end %>
  </div>
<% else %>
  <p>You haven't booked any flights.</p>
<% end %>

<div class="section-group">

  <section>
    <h3>Edit Your Details</h3>

    <%= form_for @user do |f| %>
      <div class="mb-3">
        <%= f.label :name %>
        <%= f.text_field :name, :required => true, :class => "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :email %>
        <%= f.email_field :email, :required => true, :class => "form-control"  %>
      </div>
      <div class="mb-3">
        <%= f.label :mobile %>
        <%= f.text_field :mobile, :class => "form-control"  %>
      </div>

      <!-- I might later add the option to change password by first submitting the original -->

        <%= f.submit "Edit Details", :class => "btn btn-success btn-lg" %>

    <% end %>
  </section>


    <section>
      <h3>Personal Details</h3>

      <p class="info">Name: <%= @user.name %></p>
      <p class="info">Mobile: <%= @user.mobile %></p>
      <p class="info">Email: <%= @user.email %></p>

      <%= button_to "Delete Account", @user, :method => 'delete', :class => "btn btn-danger btn-lg" %>
    </section>

</div>

<% if flash[:error] == "Cancelling Flight" %>
  <%= javascript_tag 'alert("Booking Cancelled")' %>
<% elsif flash[:error].present? %>
  <%= javascript_tag 'alert("Stop Trying to Hack Accounts. Go back to yours.")' %>  
<% end %>