config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"

  get '/flights/search' => 'flights#search', :as => 'search_flights'
  post '/flights/search' => 'flights#results', :as => 'results_flights'

  resources :users
  resources :flights

  get '/sessions/new' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  get '/sessions/destroy' => 'sessions#destroy', :as => 'sessions_destroy'

  post '/flights/book/:id' => 'flights#book', :as => 'flight_book'
  get '/flights/cancel/:id' => 'flights#cancel', :as => 'flight_cancel'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flight Planner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="/stylesheet/_bootstrap-includes.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <div class="navbar" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                <li class="nav-item" aria-current="page">
                    <%= link_to "Home", root_path, :class => "nav-link" %>
                </li>
                <% unless @current_user.present? %>
                  <li class="nav-item">
                      <%= link_to "Sign Up", new_user_path, :class => "nav-link" %> <!-- Only for users not logged in -->
                  </li>
                  <li class="nav-item">
                      <%= link_to "Log In", sessions_new_path, :class => "nav-link" %> <!-- Only for users not logged in -->
                  </li>
                <% else %>
                  <li class="nav-item">
                      <%= link_to "View Your Bookings", user_path(@current_user.id), :class => "nav-link" %> <!-- All logged in users-->
                  </li>
                  <li class="nav-item">
                      <%= link_to "Search For Flights", search_flights_path, :class => "nav-link" %> <!-- All logged in users-->
                  </li>
                  <li class="nav-item">
                      <%= link_to "View All Flights", flights_path, :class => "nav-link" %> <!-- All logged in users-->
                  </li>
                      <% if @current_user.admin? %>
                        <li class="nav-item">
                            <%= link_to "Create A New Flight", new_flight_path, :class => "nav-link" %> <!-- All logged in users-->
                        </li>
                        <li class="nav-item">
                            <%= link_to "View All Users", users_path, :class => "nav-link" %> <!-- All logged in users-->
                        </li>
                      <% end %>
                  <li class="nav-item">
                      <%= link_to "Log Out", sessions_destroy_path, :class => "nav-link" %> <!-- All logged in users-->
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>

      <div class="container">
        <h1>Flight Planner</h1>

        <%= yield %>
      </div>

  </body>
</html>